matrix:
  include:
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        # - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python --version
        - python -m pip install --upgrade pip wheel
    # - os: linux
    #   python: 3.7
    #   addons:
    #     apt:
    #       packages:
    #       - optipng  # for optimize images plugin
    #       - libjpeg-progs  # for jpegtran for optimize images plugin
    #       - tree  # for file listings
    #   before_install:
    #     - pip install --upgrade pip

sudo: false  # run on new infrastructure
# language: python
# Cache Dependencies
cache: pip

# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - invoke --list
script:
  - invoke publish-carefully
# see https://github.com/timwis/vizwit/blob/master/.travis.yml#L15-L21
# see https://travis-ci.org/MinchinWeb/blog.minchin.ca
deploy:
  provider: pages
  local_dir: ../minchinweb.github.io-master/
  target-branch: master
  skip-cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  fqdm: minchin.ca
  on:
    branch: pelican
after_script:
   - tree -aC ../minchinweb.github.io-master/
